export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Error} from './Error'
export {default as HomeLayout}  from './HomeLayout'
export {default as Dashboard} from './Dashboard'
export {default as VerifyUser} from './VerifyUser'